---

- hosts: all
  vars_files:
    - host_vars/config.yml

  pre_tasks:
    - name: Ensure apt cache is up to date.
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Make sure Git is installed
      become: true
      apt:
        name: git
        state: latest
        update_cache: yes
  roles:
    - common
    - network
    - firewall