---

- name: "Generate /etc/hosts.ansible file"
  become: true
  template: 
    src: hosts.j2
    dest: /etc/hosts.ansible
    owner: root
    group: root
    mode: 0644
  tags: network

- name: "install /etc/hosts.ansible file"
  become: true
  command: "cp /etc/hosts.ansible /etc/hosts"
  tags: network
  